language: generic
addons:
  apt:
    update: true
jobs:
  include:
    - stage: test
      env: Type='Test Checks'
      language: node_js
      node_js:
        - "8"
      before_script:
        - npm i -g add codecov
      script:
        - npm run eslint
        - npm run flow
        - npm run cover -- --runInBand
      after_success:
        - codecov
    - stage: deploy-npm
      env: Type='NPM Deploy'
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        skip_cleanup: true
        api_key: "$NPM_TOKEN"
        on:
          all_branches: true
          repo: whamcloud/number-formatters
stages:
  - test
  - name: deploy-npm
    if: branch =~ ^v\d+\.\d+\.\d+-1.*$
